interface CountryData {
  [key: string]: string;
}

interface GlobalData {
  WW_146: CountryData;
  WW_54: CountryData;
  AP: CountryData;
  EU_42: CountryData;
  EU_33: CountryData;
  AU_NZ: CountryData;
  US_CA: CountryData;
  HK_MO: CountryData;
  GU_MP: CountryData;
}

export const globalData: GlobalData = {
  WW_146: {
    SG: "Singapore",
    AU: "Australia/New Zealand",
    BG: "Bulgaria",
    BY: "Belarus",
    KH: "Cambodia",
    DZ: "Algeria",
    CM: "Cameroon",
    CA: "Canada",
    KY: "Cayman Islands",
    LK: "Sri Lanka",
    CL: "Chile",
    TW: "Taiwan",
    CO: "Columbia",
    CD: "Democratic Republic of Congo",
    CR: "Costa Rica",
    HR: "Croatia",
    CY: "Cyprus",
    CZ: "Czech Republic",
    DK: "Denmark",
    DM: "Dominica",
    DO: "Dominican Republic",
    EC: "Ecuador",
    SV: "El Salvador",
    EE: "Estonia",
    FO: "Faroe Islands",
    FI: "Finland",
    FR: "France",
    GF: "French Guiana",
    GE: "Georgia",
    DE: "Germany",
    AG: "Antigua and Barbuda",
    GH: "Ghana",
    GI: "Gibraltar",
    GR: "Greece",
    GD: "Grenada",
    AZ: "Azerbaijan",
    GU: "Guam",
    AR: "Argentina",
    GT: "Guatemala",
    GY: "Guyana",
    HT: "Haiti",
    HN: "Honduras",
    HK: "Hong Kong",
    HU: "Hungary",
    IS: "Iceland",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran",
    IE: "Ireland",
    IL: "Israel",
    IT: "Italy",
    CI: "Ivory Coast",
    JM: "Jamaica",
    JP: "Japan",
    KZ: "Kazakhstan",
    JO: "Jordan",
    KE: "Kenya",
    KR: "Korea",
    KW: "Kuwait",
    KG: "Kyrgyzstan",
    LA: "Laos",
    LV: "Latvia",
    LR: "Liberia",
    LT: "Lithuania",
    LU: "Luxembourg",
    MO: "Macau",
    MG: "Madagascar",
    MW: "Malawi",
    MY: "Malaysia",
    MT: "Malta",
    MQ: "Martinique",
    MU: "Mauritius",
    MX: "Mexico",
    MN: "Mongolia",
    MD: "Moldova",
    ME: "Montenegro",
    BD: "Bangladesh",
    MA: "Morocco",
    MZ: "Mozambique",
    AM: "Armenia",
    OM: "Oman",
    BB: "Barbados",
    NP: "Nepal",
    NL: "Netherlands",
    AW: "Aruba",
    VU: "Vanuatu",
    NZ: "New Zealand",
    NI: "Nicaragua",
    BE: "Belgium",
    NO: "Norway",
    PK: "Pakistan",
    PA: "Panama",
    PG: "Papua New Guinea",
    PY: "Paraguay",
    PE: "Peru",
    PH: "Philippines",
    PL: "Poland",
    PT: "Portugal",
    QA: "Qatar",
    RO: "Romania",
    RU: "Russia",
    RW: "Rwanda",
    AI: "Anguilla",
    LC: "Saint Lucia",
    SA: "Saudi Arabia",
    RS: "Serbia",
    SC: "Seychelles",
    SL: "Sierra Leone",
    BA: "Bosnia and Herzegovina",
    SK: "Slovakia",
    VN: "Vietnam",
    SI: "Slovenia",
    ZA: "Republic of South Africa",
    ES: "Spain",
    SZ: "Swaziland",
    SE: "Sweden",
    CH: "Switzerland",
    BR: "Brazil",
    TJ: "Tajikistan",
    TH: "Thailand",
    TO: "Tonga",
    TT: "Trinidad and Tobago",
    AE: "United Arab Emirates",
    TN: "Tunisia",
    TR: "Turkey",
    TC: "Turks and Caicos Islands",
    AL: "Albania",
    UG: "Uganda",
    UA: "Ukraine",
    EG: "Egypt",
    UK: "United Kingdom",
    TZ: "Tanzania",
    US: "USA",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    YE: "Yemen",
    VG: "British Virgin Islands",
    BN: "Brunei",
  },

  WW_54: {
    GR: "Greece",
    NL: "Netherlands",
    BE: "Belgium",
    FR: "France",
    ES: "Spain",
    HU: "Hungary",
    HR: "Croatia",
    IT: "Italy",
    RO: "Romania",
    CH: "Switzerland",
    CZ: "Czech Republic",
    SK: "Slovakia",
    AT: "Austria",
    UK: "United Kingdom",
    DK: "Denmark",
    SE: "Sweden",
    NO: "Norway",
    FI: "Finland",
    LT: "Lithuania",
    LV: "Latvia",
    EE: "Estonia",
    PL: "Poland",
    DE: "Germany",
    GI: "Gibraltar",
    PT: "Portugal",
    LU: "Luxembourg",
    IE: "Ireland",
    IS: "Iceland",
    MT: "Malta",
    CY: "Cyprus",
    BG: "Bulgaria",
    SI: "Slovenia",
    CA: "Canada",
    US: "United States",
    GU: "Guam",
    MP: "Saipan",
    PK: "Pakistan",
    AE: "United Arab Emirates",
    JP: "Japan",
    VN: "Vietnam",
    HK: "Hong Kong",
    MO: "Macau",
    KH: "Cambodia",
    CN: "China",
    TW: "Taiwan",
    MY: "Malaysia",
    AU: "Australia",
    ID: "Indonesia",
    PH: "Philippines",
    TH: "Thailand",
    SG: "Singapore",
    NZ: "New Zealand",
    ZA: "Republic of South Africa",
    BR: "Brazil",
  },

  EU_42: {
    GR: "Greece",
    NL: "Netherlands",
    BE: "Belgium",
    FR: "France",
    ES: "Spain",
    HU: "Hungary",
    BA: "Bosnia and Herzegovina",
    HR: "Croatia",
    RS: "Serbia",
    IT: "Italy",
    RO: "Romania",
    CZ: "Czech Republic",
    SK: "Slovakia",
    AT: "Austria",
    UK: "United Kingdom",
    DK: "Denmark",
    SE: "Sweden",
    NO: "Norway",
    FI: "Finland",
    LT: "Lithuania",
    LV: "Latvia",
    EE: "Estonia",
    UA: "Ukraine",
    PL: "Poland",
    DE: "Germany",
    GI: "Gibraltar",
    PT: "Portugal",
    LU: "Luxembourg",
    IE: "Ireland",
    IS: "Iceland",
    MT: "Malta",
    CY: "Cyprus",
    BG: "Bulgaria",
    SI: "Slovenia",
    AL: "Albania",
    FO: "Faroe Islands",
    GF: "French Guiana",
    GP: "Guadeloupe",
    MQ: "Martinique",
    ME: "Montenegro",
    RU: "Russia",
    CH: "Switzerland",
  },

  EU_33: {
    GR: "Greece",
    NL: "Netherlands",
    BE: "Belgium",
    FR: "France",
    ES: "Spain",
    HU: "Hungary",
    HR: "Croatia",
    IT: "Italy",
    RO: "Romania",
    CH: "Switzerland",
    CZ: "Czech Republic",
    SK: "Slovakia",
    AT: "Austria",
    UK: "United Kingdom",
    DK: "Denmark",
    SE: "Sweden",
    NO: "Norway",
    FI: "Finland",
    LT: "Lithuania",
    LV: "Latvia",
    EE: "Estonia",
    PL: "Poland",
    DE: "Germany",
    PT: "Portugal",
    LU: "Luxembourg",
    IE: "Ireland",
    IS: "Iceland",
    MT: "Malta",
    CY: "Cyprus",
    BG: "Bulgaria",
    TR: "Turkey",
    SI: "Slovenia",
    LI: "Liechtenstein"    
  },

  AP: {
    TH: "Thailand",
    ID: "Indonesia",
    SG: "Singapore",
    TW: "Taiwan",
    JP: "Japan",
    LA: "Laos",
    CN: "China",
    KH: "Cambodia",
    MY: "Malaysia",
    PH: "Philippines",
    HK: "Hong Kong",
    MO: "Macau",
    VN: "Vietnam",
  },

  US_CA: {
    US: "United States",
    CA: "Canada",
  },

  GU_MP: {
    GU: "Guam",
    MP: "Saipan",
  },

  HK_MO: {
    HK: "Hong Kong",
    MO: "Macau",
  },

  AU_NZ: {
    AU: "Australia",
    NZ: "New Zealand",
  },
};

// export const globalDataProvider: GlobalData = {
//   WW_146: {
//     AE: "United Arab Emirates",
//     AG: "Antigua and Barbuda",
//     AI: "Anguilla",
//     AL: "Albania",
//     AM: "Armenia",
//     AR: "Argentina",
//     AW: "Aruba",
//     AZ: "Azerbaijan",
//     BA: "Bosnia and Herzegovina",
//     BB: "Barbados",
//     BD: "Bangladesh",
//     BE: "Mobistar: 3G / Orange: 3G,4G / Belgacom: 3G,4G / Base: 3G,4G",
//     BG: "Bulgaria",
//     BH: "Bahrain",
//     BN: "Brunei",
//     BO: "Bolivia",
//     BR: "Brazil",
//     BY: "Belarus",
//     CA: "Canada",
//     CH: "Switzerland",
//     CI: "Ivory Coast",
//     CL: "Chile",
//     CM: "Cameroon",
//     CO: "Columbia",
//     CR: "Costa Rica",
//     CY: "Cyprus",
//     CZ: "Czech Republic",
//     DE: "Germany",
//     DJ: "Djibouti",
//     DK: "Denmark",
//     DM: "Dominica",
//     DO: "Dominican Republic",
//     DZ: "Algeria",
//     EC: "Ecuador",
//     EE: "Estonia",
//     EG: "Egypt",
//     ES: "Spain",
//     ET: "Ethiopia",
//     FI: "Finland",
//     FO: "Faroe Islands",
//     FR: "SFR: 3G,4G / BOUYGUES: 3G,4G / Orange: 3G,4G",
//     GE: "Georgia",
//     GH: "Ghana",
//     GI: "Gibraltar",
//     GL: "Greenland",
//     GM: "Gambia",
//     GN: "Guinea",
//     GP: "Guadeloupe",
//     GR: "Vodafone: 3G,4G / Cosmote: 3G,4G / Wind Hellas: 3G,4G",
//     GT: "Guatemala",
//     GU: "Guam",
//     GY: "Guyana",
//     HK: "Hong Kong",
//     HN: "Honduras",
//     HR: "Croatia",
//     HT: "Haiti",
//     HU: "Hungary",
//     ID: "Indonesia",
//     IE: "Ireland",
//     IL: "Israel",
//     IN: "India",
//     IR: "Iran",
//     IS: "Iceland",
//     IT: "Italy",
//     JM: "Jamaica",
//     JO: "Jordan",
//     JP: "Japan",
//     KE: "Kenya",
//     KG: "Kyrgyzstan",
//     KH: "Cambodia",
//     KI: "Kiribati",
//     KM: "Comoros",
//     KN: "Saint Kitts and Nevis",
//     KR: "Korea",
//     KW: "Kuwait",
//     KY: "Cayman Islands",
//     KZ: "Kazakhstan",
//     LA: "Laos",
//     LC: "Saint Lucia",
//     LK: "Sri Lanka",
//     LR: "Liberia",
//     LS: "Lesotho",
//     LT: "Lithuania",
//     LU: "Luxembourg",
//     LV: "Latvia",
//     MA: "Morocco",
//     MD: "Moldova",
//     MG: "Madagascar",
//     MK: "North Macedonia",
//     ML: "Mali",
//     MO: "Macau",
//     MQ: "Martinique",
//     MR: "Mauritania",
//     MS: "Montserrat",
//     MT: "Malta",
//     MU: "Mauritius",
//     MV: "Maldives",
//     MW: "Malawi",
//     MX: "Mexico",
//     MY: "Malaysia",
//     MZ: "Mozambique",
//     NA: "Namibia",
//     NE: "Niger",
//     NG: "Nigeria",
//     NI: "Nicaragua",
//     NL: "T-Mobile: 3G / Vodafone: 4G / KPN: 3G,4G",
//     NO: "Norway",
//     NP: "Nepal",
//     NZ: "New Zealand",
//     OM: "Oman",
//     PA: "Panama",
//     PE: "Peru",
//     PG: "Papua New Guinea",
//     PH: "Philippines",
//     PK: "Pakistan",
//     PL: "Poland",
//     PT: "Portugal",
//     PY: "Paraguay",
//     QA: "Qatar",
//     RE: "Réunion",
//     RO: "Romania",
//     RS: "Serbia",
//     RU: "Russia",
//     RW: "Rwanda",
//     SA: "Saudi Arabia",
//     SC: "Seychelles",
//     SD: "Sudan",
//     SE: "Sweden",
//     SG: "Singapore",
//     SI: "Slovenia",
//     SK: "Slovakia",
//     SL: "Sierra Leone",
//     SN: "Senegal",
//     SR: "Suriname",
//     SV: "El Salvador",
//     SZ: "Swaziland",
//     TC: "Turks and Caicos Islands",
//     TD: "Chad",
//     TG: "Togo",
//     TH: "Thailand",
//     TJ: "Tajikistan",
//     TM: "Turkmenistan",
//     TN: "Tunisia",
//     TO: "Tonga",
//     TR: "Turkey",
//     TT: "Trinidad and Tobago",
//     TW: "Taiwan",
//     TZ: "Tanzania",
//     UG: "Uganda",
//     UK: "United Kingdom",
//     UY: "Uruguay",
//     US: "USA",
//     UZ: "Uzbekistan",
//     VA: "Vatican City",
//     VC: "Saint Vincent and the Grenadines",
//     VE: "Venezuela",
//     VG: "British Virgin Islands",
//     VI: "U.S. Virgin Islands",
//     VN: "Vietnam",
//     VU: "Vanuatu",
//     WS: "Samoa",
//     YE: "Yemen",
//     ZA: "Republic of South Africa",
//     ZM: "Zambia",
//     ZW: "Zimbabwe",
//   },
// };
