export const globalProvider = {
  WW_146: {
    GR: "Vodafone: 3G,4G / Cosmote: 3G,4G / Wind Hellas: 3G,4G",
    NL: "T-Mobile: 3G / Vodafone: 4G / KPN: 3G,4G",
    BE: "Mobistar: 3G / Orange: 3G,4G / Belgacom: 3G,4G / Base: 3G,4G",
    FR: "SFR: 3G,4G / BOUYGUES: 3G,4G / Orange: 3G,4G",
    ES: "Orange: 3G,4G / Telefonica: 3G,4G / Xfera: 3G,4G / Vodafone: 3G,4G",
    HU: "T-mobile: 3G,4G / Telenor: 3G,4G / Vodafone: 3G,4G",
    BA: "HT: 3G,4G / BH Telecom: 3G,4G",
    HR: "T-mobile: 3G,4G / A1 Hrvatska: 3G,4G / Telemach: 3G,4G",
    RS: "Telenor: 3G,4G / Telekom: 3G,4G / Telenor: 3G,4G / A1: 3G,4G",
    IT: "WIND: 3G,4G / Vodafone: 3G,4G / TIM: 3G,4G / H3G: 3G / Iliad Italia: 3G,4G",
    RO: "Vodafone: 3G,4G",
    CH: "Sunrise: 3G,4G / Orange: 3G",
    CZ: "Vodafone: 4G / T-mobile: 3G / Cetin: 4G",
    SK: "Telefonica O2: 3G / Orange: 3G,4G / Orange Slovensko: 3G,4G",
    AT: "T-mobile: 3G,4G / Orange: 3G,4G / A1: 3G,4G",
    UK: "Vodafone: 4G / EE: 3G,4G / Telefonica O2: 3G,4G / Hutchison: 3G,4G",
    DK: "TDC: 3G,4G / Telia: 3G,4G / Telenor: 3G / Hi3G Danemark: 3G,4G",
    SE: "Telenor: 3G,4G / TeliaSonera: 3G,4G / Tele2: 3G,4G",
    NO: "Telia: 4G / Telenor: 4G",
    FI: "Elisa: 3G,4G / Alcom: 3G,4G / DNA: 3G,4G",
    LT: "UAB BITE: 3G / Tele2: 3G,4G",
    LV: "SIA BITE: 3G,4G / Tele2: 3G,4G",
    EE: "Tele2: 3G / Elisa EMT: 3G,4G",
    RU: "MTS: 3G,4G / MegaFon: 3G / VimpelCom: 3G,4G / T2 Mobile: 3G",
    UA: "Vodafone: 3G / Kyivstar: 3G,4G",
    BY: "FE VELCOM: 3G",
    MD: "Orange: 3G,4G",
    PL: "Orange: 3G,4G / T-mobile: 3G / Polkomtel: 3G,4G / P4: 3G",
    DE: "Vodafone: 3G,4G / Telefonica O2: 3G,4G",
    GI: "Gibtel: 3G,4G",
    PT: "TMN: 3G / Optimus: 3G,4G / Vodafone: 3G,4G / NOS: 3G,4G",
    LU: "TANGO: 3G,4G / P&T: 3G,4G / Orange: 3G",
    IE: "Meteor: 3G,4G / Hutchison: 3G,4G",
    IS: "Siminn: 3G,4G / Nova: 3G,4G",
    AL: "Vodafone: 3G,4G",
    MT: "Epic: 3G,4G / GO: 3G,4G",
    CY: "EPIC: 3G,4G / CYTA: 3G,4G",
    GE: "Geocell: 4G",
    AM: "ArmenTel: 3G,4G",
    BG: "MOBILTEL: 3G,4G / Yettel: 3G,4G",
    TR: "Turkcell: 3G,4G",
    FO: "Faroese Telecom: 3G,4G",
    SI: "Telekom: 3G,4G / Telemach: 3G,4G / A1: 3G,4G",
    ME: "Telenor: 3G,4G",
    CA: "Bell: 3G,4G / Telus: 3G,4G / Sasktel: 3G / Rogers: 3G,4G",
    US: "AT&T: 4G / T-Mobile: 3G,4G",
    GU: "Docomo Pacific: 3G,4G",
    MX: "Telefonica: 3G,4G / Telcel: 3G,4G",
    JM: "Digicel: 3G,4G",
    BM: "Digicel: 3G,4G",
    HT: "Digicel: 3G,4G",
    MQ: "Digicel: 3G,4G",
    GF: "Digicel: 3G,4G",
    BB: "Digicel: 3G,4G",
    AG: "Digicel: 3G,4G",
    KY: "Digicel: 3G,4G",
    VG: "Digicel: 3G,4G",
    GD: "Digicel: 3G,4G",
    KN: "Digicel: 3G,4G",
    LC: "Digicel: 3G,4G",
    VC: "Digicel: 3G,4G",
    BQ: "Digicel: 3G,4G",
    AW: "Digicel: 3G,4G",
    AI: "Digicel: 3G,4G",
    DM: "Digicel: 3G,4G",
    DO: "Digicel: 3G,4G",
    TT: "Digicel: 3G,4G",
    TC: "Digicel: 3G,4G",
    AZ: "Azercell: 3G,4G",
    KZ: "Tele2: 3G,4G",
    IN: "Airtel: 3G,4G",
    PK: "CMPak: 4G",
    LK: "Digicel: 3G,4G",
    JO: "Zain: 3G,4G",
    KW: "Ooredoo: 3G,4G",
    SA: "Etihad Etisalat: 3G,4G",
    YE: "MTN:",
    OM: "Ooredoo : 3G,4G",
    AE: "Etisalat: 3G,4G / DU: 3G,4G",
    IL: "Partner: 3G / Cellcom: 3G,4G / Pelephone: 3G,4G",
    QA: "Qtel: 3G,4G",
    MN: "Qtel: 3G,4G",
    NP: "Nepal Telecom: 3G,4G",
    IR: "MTN Irancell: 3G,4G",
    UZ: "Unitel: 3G,4G",
    TJ: "Beeline: 3G",
    KG: "Sky Mobile: 3G,4G",
    JP: "KDDI: 4G / Softbank: 3G,4G",
    KR: "KT: 3G,4G",
    VN: "Viettel: 3G,4G / Vinaphone: 3G,4G / Mobifone: 3G,4G",
    HK: "CMHK: 3G,4G",
    MO: "CTM: 3G,4G",
    KH: "CamGSM: 4G / Smart: 4G",
    LA: "LTC: 3G",
    TW: "Chunghwa: 3G,4G",
    BD: "GrameenPhone: 3G",
    MY: "Maxis: 4G / Celcom: 3G,4G",
    AU: "Optus: 3G,4G",
    ID: "XL: 4G / Indosat: 3G,4G",
    PH: "Smart: 3G / 4G",
    TH: "Truemoe: 3G,4G",
    SG: "Singtel: 3G,4G",
    BN: "UNN: 3G,4G",
    NZ: "Spark: 3G,4G / Vodafone: 4G / NZC: 3G,4G",
    PG: "Digicel: 3G,4G",
    TO: "Digicel: 4G",
    VU: "Digicel: 4G",
    FJ: "Digicel: 3G,4G",
    EG: "Vodafone: 3G,4G / Orange: 3G,4G",
    DZ: "Mobilis: 3G,4G",
    MA: "Meditel: 3G,4G",
    TN: "Ooredoo: 3G,4G / Tunisie Telecom: 3G,4G",
    CI: "MTN: 3G,4G",
    MU: "Emtel: 3G",
    LR: "Cellcom Liberia: 3G",
    SL: "Orange: 3G",
    GH: "MTN: 3G,4G",
    CF: "Orange: 3G",
    CM: "Orange: 3G,4G / MTN: 3G,4G",
    CD: "Airtel: 3G,4G",
    SC: "Airtel: 3G,4G",
    SD: "MTN: 3G",
    RW: "MTN SA: 3G,4G / Vodacom: 3G,4G",
    KE: "Claro: 3G,4G / Telefonica: 3G",
    TZ: "Claro: 3G,4G",
    UG: "Claro: 3G,4G / Telefonica: 3G",
    MZ: "VIVO: 3G,4G",
    MG: "Claro: 3G,4G / Telefonica: 3G",
    MW: "Telefonica: 4G / Comcel: 3G",
    SZ: "-",
    ZA: "Digicel: 3G,4G",
    GT: "Azercell: 3G,4G",
    SV: "Tele2: 3G,4G",
    HN: "Airtel: 3G,4G",
    NI: "CMPak: 4G",
    CR: "Digicel: 3G,4G",
    PA: "Zain: 3G,4G",
    PE: "Ooredoo: 3G,4G",
    AR: "Etihad Etisalat: 3G,4G",
    BR: "MTN:",
    CL: "Ooredoo : 3G,4G",
    CO: "Etisalat: 3G,4G / DU: 3G,4G",
    GY: "Partner: 3G / Cellcom: 3G,4G / Pelephone: 3G,4G",
    EC: "Qtel: 3G,4G",
    PY: "Qtel: 3G,4G",
    UY: "Nepal Telecom: 3G,4G",
    GP: "MTN Irancell: 3G,4G",
    ZM: "Unitel: 3G,4G",
  },
  // missing swaziland

  WW_54: {
    GR: "Vodafone: 3G,4G / Cosmote: 3G,4G / Wind Hellas: 3G,4G",
    NL: "T-Mobile: 3G / Vodafone: 4G / KPN: 3G,4G",
    BE: "Mobistar: 3G / Orange: 3G,4G / Belgacom: 3G,4G / Base: 3G,4G",
    FR: "SFR: 3G,4G / BOUYGUES: 3G,4G / Orange: 3G,4G",
    ES: "Orange: 3G,4G / Telefonica: 3G,4G / Xfera: 3G,4G / Vodafone: 3G,4G",
    HU: "T-mobile: 3G,4G / Telenor: 3G,4G / Vodafone: 3G,4G",
    HR: "T-mobile: 3G,4G / A1 Hrvatska: 3G,4G / Telemach: 3G,4G",
    IT: "WIND: 3G,4G / Vodafone: 3G,4G / TIM: 3G,4G / H3G: 3G / Iliad Italia: 3G,4G",
    RO: "Vodafone: 3G,4G",
    CH: "Sunrise: 3G,4G / Orange: 3G",
    CZ: "Vodafone: 4G / T-mobile: 3G / Cetin: 4G",
    SK: "Telefonica O2: 3G / Orange: 3G,4G / Orange Slovensko: 3G,4G",
    AT: "T-mobile: 3G,4G / Orange: 3G,4G / A1: 3G,4G",
    UK: "Vodafone: 4G / EE: 3G,4G / Telefonica O2: 3G,4G / Hutchison: 3G,4G",
    DK: "TDC: 3G,4G / Telia: 3G,4G / Telenor: 3G / Hi3G Danemark: 3G,4G",
    SE: "Telenor: 3G,4G / TeliaSonera: 3G,4G / Tele2: 3G,4G",
    NO: "Telia: 4G / Telenor: 4G",
    FI: "Elisa: 3G,4G / Alcom: 3G,4G / DNA: 3G,4G",
    LT: "UAB BITE: 3G / Tele2: 3G,4G",
    LV: "SIA BITE: 3G,4G / Tele2: 3G,4G",
    EE: "Tele2: 3G / Elisa EMT: 3G,4G",
    PL: "Orange: 3G,4G / T-mobile: 3G / Polkomtel: 3G,4G / P4: 3G",
    DE: "Vodafone: 3G,4G / Telefonica O2: 3G,4G",
    GI: "Gibtel: 3G,4G",
    PT: "TMN: 3G / Optimus: 3G,4G / Vodafone: 3G,4G / NOS: 3G,4G",
    LU: "TANGO: 3G,4G / P&T: 3G,4G / Orange: 3G",
    IE: "Meteor: 3G,4G / Hutchison: 3G,4G",
    IS: "Siminn: 3G,4G / Nova: 3G,4G",
    MT: "Epic: 3G,4G / GO: 3G,4G",
    CY: "EPIC: 3G,4G / CYTA: 3G,4G",
    BG: "MOBILTEL: 3G,4G / Yettel: 3G,4G",
    SI: "Telekom: 3G,4G / Telemach: 3G,4G / A1: 3G,4G",
    CA: "Bell: 3G,4G / Telus: 3G,4G / Sasktel: 3G / Rogers: 3G,4G",
    US: "AT&T: 4G / T-Mobile: 3G,4G",
    GU: "Docomo Pacific: 3G,4G",
    MP: "Docomo Pacific: 3G,4G",
    PK: "CMPak: 4G",
    AE: "Etisalat: 3G,4G / DU: 3G,4G",
    JP: "KDDI: 4G / Softbank: 3G,4G",
    VN: "Viettel: 3G,4G / Vinaphone: 3G,4G / Mobifone: 3G,4G",
    HK: "CMHK: 3G,4G",
    MO: "CTM: 3G,4G",
    KH: "CamGSM: 4G / Smart: 4G",
    CN: "CMCC: 3G,4G",
    TW: "Chunghwa: 3G,4G",
    MY: "Maxis: 4G / Celcom: 3G,4G",
    AU: "Optus: 3G,4G",
    ID: "XL: 4G / Indosat: 3G,4G",
    PH: "Smart: 3G / 4G",
    TH: "Truemoe: 3G,4G",
    SG: "Singtel: 3G,4G",
    NZ: "Spark: 3G,4G / Vodafone: 4G / NZC: 3G,4G",
    ZA: "MTN SA: 3G,4G / Vodacom: 3G,4G",
    BR: "VIVO: 3G,4G",
  },
  // missing thailand and saipan

  EU_42: {
    GR: "Vodafone: 3G,4G / Cosmote: 3G,4G / Wind Hellas: 3G,4G",
    NL: "T-Mobile: 3G / Vodafone: 4G / KPN: 3G,4G",
    BE: "Mobistar: 3G / Orange: 3G,4G / Belgacom: 3G,4G / Base: 3G,4G",
    FR: "SFR: 3G,4G / BOUYGUES: 3G,4G / Orange: 3G,4G",
    ES: "Orange: 3G,4G / Telefonica: 3G,4G / Xfera: 3G,4G / Vodafone: 3G,4G",
    HU: "T-mobile: 3G,4G / Telenor: 3G,4G / Vodafone: 3G,4G",
    HR: "HT: 3G,4G / BH Telecom: 3G,4G",
    IT: "T-mobile: 3G,4G / A1 Hrvatska: 3G,4G / Telemach: 3G,4G",
    RO: "Telenor: 3G,4G / Telekom: 3G,4G / Telenor: 3G,4G / A1: 3G,4G",
    CH: "WIND: 3G,4G / Vodafone: 3G,4G / TIM: 3G,4G / H3G: 3G / Iliad Italia: 3G,4G",
    CZ: "Vodafone: 3G,4G",
    SK: "Vodafone: 4G / T-mobile: 3G / Cetin: 4G",
    AT: "Telefonica O2: 3G / Orange: 3G,4G / Orange Slovensko: 3G,4G",
    UK: "T-mobile: 3G,4G / Orange: 3G,4G / A1: 3G,4G",
    DK: "Vodafone: 4G / EE: 3G,4G / Telefonica O2: 3G,4G / Hutchison: 3G,4G",
    SE: "TDC: 3G,4G / Telia: 3G,4G / Telenor: 3G / Hi3G Danemark: 3G,4G",
    NO: "Telenor: 3G,4G / TeliaSonera: 3G,4G / Tele2: 3G,4G",
    FI: "Telia: 4G / Telenor: 4G",
    LT: "Elisa: 3G,4G / Alcom: 3G,4G / DNA: 3G,4G",
    LV: "UAB BITE: 3G / Tele2: 3G,4G",
    EE: "SIA BITE: 3G,4G / Tele2: 3G,4G",
    PL: "Tele2: 3G / Elisa EMT: 3G,4G",
    DE: "Vodafone: 3G / Kyivstar: 3G,4G",
    GI: "Orange: 3G,4G / T-mobile: 3G / Polkomtel: 3G,4G / P4: 3G",
    PT: "Vodafone: 3G,4G / Telefonica O2: 3G,4G",
    LU: "Gibtel: 3G,4G",
    IE: "TMN: 3G / Optimus: 3G,4G / Vodafone: 3G,4G / NOS: 3G,4G",
    IS: "TANGO: 3G,4G / P&T: 3G,4G / Orange: 3G",
    MT: "Meteor: 3G,4G / Hutchison: 3G,4G",
    CY: "Siminn: 3G,4G / Nova: 3G,4G",
    BG: "Epic: 3G,4G / GO: 3G,4G",
    SI: "EPIC: 3G,4G / CYTA: 3G,4G",
    CA: "MOBILTEL: 3G,4G / Yettel: 3G,4G",
    US: "Telekom: 3G,4G / Telemach: 3G,4G / A1: 3G,4G",
    GU: "Vodafone: 3G,4G",
    MP: "Faroese Telecom: 3G,4G",
    PK: "Digicel: 3G,4G",
    AE: "Digicel: 3G,4G",
    JP: "Digicel: 3G,4G",
    VN: "Telenor: 3G,4G",
    HK: "MTS: 3G,4G / MegaFon: 3G / VimpelCom: 3G,4G / T2 Mobile: 3G",
    MO: "Sunrise: 3G,4G / Orange: 3G",
  },

  EU_33: {
    GR: "Cosmote / Wind: 4G,5G",
    NL: "KPN / T Mobile: 4G, 5G",
    BE: "Proximus / Orange / Base: 4G,5G",
    FR: "Orange / Vivendi / Bouygues Telecom / Free Mobile: 4G,5G",
    ES: "Orange / Movistar / Yoigo: 4G,5G",
    HU: "Telenor Hungary: 4G,5G",
    HR: "Telemach / Hrvatski Telekom d.d. / A1 HR: 4G,5G",
    IT: "Wind: 4G,5G",
    RO: "Orange / Digi.Mobil / Telekom: 4G,5G",
    CH: "Swisscom / Sunrise: 4G,5G",
    CZ: "O2 / T-Mobile: 4G,5G",
    SK: "Orange / O2 / Telekom: 4G,5G",
    AT: "3: 4G,5G",
    UK: "O2 / T-Mobile: 4G,5G",
    DK: "TDC / 3 / Telenor / Telia / TT-Netværket P/S: 4G,5G",
    SE: "Telia / 3 / Tele2 / Telenor: 4G,5G",
    NO: "Telia / Telenor: 4G,5G",
    FI: "Elisa: 3G,4G",
    LT: "BITE / Alcom / Telia / SAMK / DNA: 4G,5G",
    LV: "LMT / Tele2 / Bite: 4G,5G",
    EE: "Tele2 / Elisa / Telia: 4G,5G",
    PL: "Orange / Plus / T-Mobile / Play: 4G,5G",
    DE: "O2 / Telekom: 4G,5G",
    PT: "NOS / MEO: 4G,5G",
    LU: "Orange / Tango / POST: 4G,5G",
    IE: "3: 4G,5G",
    IS: "Siminn / Nova: 4G,5G",
    MT: "Melita / GO: 4G,5G",
    CY: "Vodafone / PrimeTel / Epic: 4G,5G",
    BG: "Telenor / Vivacom: 4G,5G",
    TR: "Turkcell / Turk Telekom: 4G,5G",
    SI: "Mobitel / Telemach / A1: 4G,5G",
    LI: "FL1: 4G"    
  },

  AP: {
    TH: "Truemoe: 3G,4G",
    ID: "XL: 4G / Indosat: 3G,4G",
    SG: "Singtel: 3G,4G",
    TW: "Chunghwa: 3G,4G",
    JP: "KDDI: 4G / Softbank: 3G,4G",
    LA: "LTC: 3G",
    CN: "CMCC: 3G,4G",
    MO: "CamGSM: 4G / Smart: 4G",
    MY: "Maxis: 4G / Celcom: 3G,4G",
    PH: "Smart: 3G / 4G",
    HK: "CMHK: 3G,4G",
    VN: "CTM: 3G,4G",
  },
};
