
interface CountryData {
    [key: string]: string;
  }
  
  interface GlobalData {
    WW_146: CountryData;
    WW_54: CountryData;
    AP: CountryData;
    EU_42: CountryData;
    EU_33: CountryData;
    AU_NZ: CountryData;
    US_CA: CountryData;
    HK_MO: CountryData;
    GU_MP: CountryData;
  }


export const globalData: GlobalData = {
    WW_146: {
        SG: "Singapore",
        AU: "Australia/New Zealand",
        BG: "Bulgaria",
        BY: "Belarus",
        KH: "Cambodia",
        DZ: "Algeria",
        CM: "Cameroon",
        CA: "Canada",
        KY: "Cayman Islands",
        LK: "Sri Lanka",
        CL: "Chile",
        TW: "Taiwan",
        CO: "Columbia",
        CD: "Democratic Republic of Congo",
        CR: "Costa Rica",
        HR: "Croatia",
        CY: "Cyprus",
        CZ: "Czech Republic",
        DK: "Denmark",
        DM: "Dominica",
        DO: "Dominican Republic",
        EC: "Ecuador",
        SV: "El Salvador",
        EE: "Estonia",
        FO: "Faroe Islands",
        FI: "Finland",
        FR: "France",
        GF: "French Guiana",
        GE: "Georgia",
        DE: "Germany",
        AG: "Antigua and Barbuda",
        GH: "Ghana",
        GI: "Gibraltar",
        GR: "Greece",
        GD: "Grenada",
        AZ: "Azerbaijan",
        GU: "Guam",
        AR: "Argentina",
        GT: "Guatemala",
        GY: "Guyana",
        HT: "Haiti",
        HN: "Honduras",
        HK: "Hong Kong",
        HU: "Hungary",
        IS: "Iceland",
        IN: "India",
        ID: "Indonesia",
        IR: "Iran",
        IE: "Ireland",
        IL: "Israel",
        IT: "Italy",
        CI: "Ivory Coast",
        JM: "Jamaica",
        JP: "Japan",
        KZ: "Kazakhstan",
        JO: "Jordan",
        KE: "Kenya",
        KR: "Korea",
        KW: "Kuwait",
        KG: "Kyrgyzstan",
        LA: "Laos",
        LV: "Latvia",
        LR: "Liberia",
        LT: "Lithuania",
        LU: "Luxembourg",
        MO: "Macau",
        MG: "Madagascar",
        MW: "Malawi",
        MY: "Malaysia",
        MT: "Malta",
        MQ: "Martinique",
        MU: "Mauritius",
        MX: "Mexico",
        MN: "Mongolia",
        MD: "Moldova",
        ME: "Montenegro",
        BD: "Bangladesh",
        MA: "Morocco",
        MZ: "Mozambique",
        AM: "Armenia",
        OM: "Oman",
        BB: "Barbados",
        NP: "Nepal",
        NL: "Netherlands",
        AW: "Aruba",
        VU: "Vanuatu",
        NZ: "New Zealand",
        NI: "Nicaragua",
        BE: "Belgium",
        NO: "Norway",
        PK: "Pakistan",
        PA: "Panama",
        PG: "Papua New Guinea",
        PY: "Paraguay",
        PE: "Peru",
        PH: "Philippines",
        PL: "Poland",
        PT: "Portugal",
        QA: "Qatar",
        RO: "Romania",
        RU: "Russia",
        RW: "Rwanda",
        AI: "Anguilla",
        LC: "Saint Lucia",
        SA: "Saudi Arabia",
        RS: "Serbia",
        SC: "Seychelles",
        SL: "Sierra Leone",
        BA: "Bosnia and Herzegovina",
        SK: "Slovakia",
        VN: "Vietnam",
        SI: "Slovenia",
        ZA: "Republic of South Africa",
        ES: "Spain",
        SZ: "Swaziland",
        SE: "Sweden",
        CH: "Switzerland",
        BR: "Brazil",
        TJ: "Tajikistan",
        TH: "Thailand",
        TO: "Tonga",
        TT: "Trinidad and Tobago",
        AE: "United Arab Emirates",
        TN: "Tunisia",
        TR: "Turkey",
        TC: "Turks and Caicos Islands",
        AL: "Albania",
        UG: "Uganda",
        UA: "Ukraine",
        EG: "Egypt",
        UK: "United Kingdom",
        TZ: "Tanzania",
        US: "USA",
        UY: "Uruguay",
        UZ: "Uzbekistan",
        YE: "Yemen",
        VG: "British Virgin Islands",
        BN: "Brunei"
    },
    WW_54: {
        BG: "Bulgaria",
        KH: "Cambodia",
        CA: "Canada",
        CN: "China",
        TW: "Taiwan",
        HR: "Croatia",
        CY: "Cyprus",
        CZ: "Czech Republic",
        DK: "Denmark",
        EE: "Estonia",
        FI: "Finland",
        FR: "France",
        DE: "Germany",
        GI: "Gibraltar",
        GR: "Greece",
        GU: "Guam",
        MP: "Saipan",
        HK: "Hong Kong",
        HU: "Hungary",
        IS: "Iceland",
        AU: "Australia",
        ID: "Indonesia",
        IE: "Ireland",
        IT: "Italy",
        JP: "Japan",
        AT: "Austria",
        LV: "Latvia",
        LT: "Lithuania",
        LU: "Luxembourg",
        MO: "Macau",
        MY: "Malaysia",
        MT: "Malta",
        NL: "Netherlands",
        NZ: "New Zealand",
        BE: "Belgium",
        NO: "Norway",
        PK: "Pakistan",
        PH: "Philippines",
        PL: "Poland",
        PT: "Portugal",
        RO: "Romania",
        SG: "Singapore",
        SK: "Slovakia",
        VN: "Vietnam",
        SI: "Slovenia",
        ZA: "Republic of South Africa",
        ES: "Spain",
        SE: "Sweden",
        CH: "Switzerland",
        BR: "Brazil",
        AE: "United Arab Emirates",
        UK: "United Kingdom",
        US: "USA"
    },
    AP: {
        KH: "Cambodia",
        CN: "China",
        TW: "Taiwan",
        HK: "Hong Kong",
        ID: "Indonesia",
        JP: "Japan",
        LA: "Laos",
        MO: "Macau",
        MY: "Malaysia",
        PH: "Philippines",
        SG: "Singapore",
        VN: "Vietnam",
        TH: "Thailand"
    },
    EU_42: {
        BG: "Bulgaria",
        HR: "Croatia",
        CY: "Cyprus",
        CZ: "Czech Republic",
        DK: "Denmark",
        EE: "Estonia",
        FO: "Faroe Islands",
        FI: "Finland",
        FR: "France",
        GF: "French Guiana",
        DE: "Germany",
        GI: "Gibraltar",
        GR: "Greece",
        GP: "Guadeloupe",
        HU: "Hungary",
        IS: "Iceland",
        IE: "Ireland",
        IT: "Italy",
        AT: "Austria",
        LV: "Latvia",
        LT: "Lithuania",
        LU: "Luxembourg",
        MT: "Malta",
        MQ: "Martinique",
        ME: "Montenegro",
        NL: "Netherlands",
        BE: "Belgium",
        NO: "Norway",
        PL: "Poland",
        PT: "Portugal",
        RO: "Romania",
        RU: "Russia",
        RS: "Serbia",
        BA: "Bosnia and Herzegovina",
        SK: "Slovakia",
        SI: "Slovenia",
        ES: "Spain",
        SE: "Sweden",
        CH: "Switzerland",
        AL: "Albania",
        UA: "Ukraine",
        UK: "United Kingdom"
    },
    EU_33: {
        BG: "Bulgaria",
        HR: "Croatia",
        CY: "Cyprus",
        CZ: "Czech Republic",
        DK: "Denmark",
        EE: "Estonia",
        FI: "Finland",
        FR: "France",
        DE: "Germany",
        GR: "Greece",
        HU: "Hungary",
        IS: "Iceland",
        IE: "Ireland",
        IT: "Italy",
        AT: "Austria",
        LV: "Latvia",
        LI: "Liechtenstein",
        LT: "Lithuania",
        LU: "Luxembourg",
        MT: "Malta",
        NL: "Netherlands",
        BE: "Belgium",
        NO: "Norway",
        PL: "Poland",
        PT: "Portugal",
        RO: "Romania",
        SK: "Slovakia",
        SI: "Slovenia",
        ES: "Spain",
        SE: "Sweden",
        CH: "Switzerland",
        TR: "Turkey",
        UK: "United Kingdom"
    },
    US_CA: {
        US: "United States",
        CA: "Canada"
    },
    GU_MP: {
        GU: "Guam",
        MP: "Saipan"
    },
    HK_MO: {
        HK: "Hong Kong",
        MO: "Macau"
    },
    AU_NZ: {
        AU: "Australia",
        NZ: "New Zealand"
    }
}