FROM node:18.17-alpine
WORKDIR /app

ARG NEXT_PUBLIC_HOST_API
ARG NEXT_PUBLIC_GOOGLE_ID
ARG NEXT_PUBLIC_SMARTLOOK

ENV NEXT_PUBLIC_HOST_API=${NEXT_PUBLIC_HOST_API}
ENV NEXT_PUBLIC_PAYPAL_CLIENT_ID=${NEXT_PUBLIC_PAYPAL_CLIENT_ID}

COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY . .

RUN yarn run build

ENV NODE_ENV production

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "start"]
